### ISSUE TITLE
1738A: Glory Addicts

### ISSUE THREAD

**Issue by pstreemaze** [pstreemaze/Codeforces-problems#1]
Add optimised solution for https://codeforces.com/problemset/problem/1738/A problem of codeforces

**Comment by akhilchoudhary2k** [comment]
@pstreemaze Raised a PR: https://github.com/pstreemaze/Codeforces-problems/pull/20

**Comment by ShrutikaK2911** [comment]
Can I work on this issue? @pstreemaze
