### ISSUE TITLE
49. Group Anagrams Leetcode Question

### ISSUE THREAD

**Issue by pstreemaze** [pstreemaze/Codeforces-problems#9]
Add solution for [49. Group Anagrams](https://leetcode.com/problems/group-anagrams/)

**Comment by srdhal** [comment]
@pstreemaze Can you assign me this issue? I want to work on it.

**Comment by akhilchoudhary2k** [comment]
@pstreemaze  raised a PR: https://github.com/pstreemaze/Codeforces-problems/pull/18
